### ISSUE TITLE
Привет, нужна помощь

### ISSUE THREAD

**Issue by Hacker2k19** [Bainky/Telegram-RAT#11]
Почему, у меня постоянно "Нет подключения"
В более старых версиях мне выдавало ошибку, писало что не удаётся соединиться, теперь же мне прямым текстом пишет, что нет подключения
![екуке](https://user-images.githubusercontent.com/48107204/80559915-c4c64400-89e7-11ea-9a09-1b8be2a50112.PNG)

**Comment by Bainky** [comment]
Привет, телега заблокирована на территории РФ, насчет этого могу только посочувствовать и посоветовать использовать прокси.

`pip install pysocks`

https://hidemy.name/ru/proxy-list/

`apihelper.proxy` = {'https':'socks5://proxy_address:port'}`

**Comment by al000al** [comment]
у меня так было,сменить API у бота надо
