### ISSUE TITLE
Ошибка запуска exe. 

### ISSUE THREAD

**Issue by MekoNix** [Bainky/Telegram-RAT#12]
Установил всё без ошибок, но после запуска exe файла появляется вот такая ошибка.  
![image](https://user-images.githubusercontent.com/64309709/80695510-af801100-8ade-11ea-8975-fa28713357d3.png)
Тестировал на Windows 10, Windows7, Windows8. Везде такая же ошибка.
Кто смог решить помогите пожалуйста. Заранее спасибо.

**Comment by Bainky** [comment]
Не могли бы вы скомпилировать файл без `--noconsole` и прислать лог ошибки?

**Comment by MekoNix** [comment]
Заранее извиняюсь за долгий ответ. 
Вот лог.
![image](https://user-images.githubusercontent.com/64309709/80728023-2208e500-8b0f-11ea-81e4-09aba9fccbfc.png)

**Comment by Bainky** [comment]
Установите модуль pyperclip

**Comment by MekoNix** [comment]
Произошла ошибка в установке модуля pyperclip 
Could not build wheels for pyperclip, since package 'wheel' is not installed. 
Не знаете как установить некий пакет "wheel"

**Comment by MekoNix** [comment]
После установки модуля выдаёт  ошибку No module named pyperclip.

**Comment by MekoNix** [comment]
Не получилось!
Установил pyperclip но сначала надо установить wheel в такой последовательности. 
pip install wheel 
pip install pyperclip

**Comment by MekoNix** [comment]
Нашёл решение ошибки. Нужно установить pysocks. ** После запуска нечего не происходит**
pip install wheel 
pip install pyperclip
pip install pysocks

**Comment by MekoNix** [comment]
Нашёл решение ошибки. Нужно установить pysocks. Я так и не понял ошибки возможно ему был не обходим pysocks но выводился pyperclip.
pip install wheel 
pip install pyperclip
