### ISSUE TITLE
Сделайте requirments.txt

### ISSUE THREAD

**Issue by MikhailKhromov** [Bainky/Telegram-RAT#13]
И в ридми поставьте pip3 install -r requirements.txt
Зачем прописывать каждый файл руками?

**Comment by Bainky** [comment]
Спасибо за идею! Но в скрипте имеется небольшая проблема с `pyaudio`. Из-за этого через текстовик её не получится установить.

**Comment by CrmDev** [comment]
Тогда в батник, пару файлов конечно придётся скачать вручную:

pip3 install pytelegrambotapi
pip3 install opencv-python
pip3 install cryptography
pip3 install pyperclip
pip3 install comtypes
pip3 install pywin32
pip3 install PyAudio-0.2.11-cp38-cp38-win32.whl
pip3 install pillow
pip3 install pycaw
pip3 install pysocks
pip install PyInstaller-3.6-py2.py3-none-any.whl
pip uninstall -y enum34

**Comment by MikhailKhromov** [comment]
Батник подойдет только для винды, лучше setup.py. В нем либо через requests (скорее всего так и так установлено, а если нет то будет установлено потом) скачать .whl файлы, и остальные через pip установить.
