### ISSUE TITLE
Failed to execute script RAT

### ISSUE THREAD

**Issue by deadxxxxinside** [Bainky/Telegram-RAT#14]
![image](https://user-images.githubusercontent.com/64790180/82059758-ea3d9800-96df-11ea-868e-e7573a7e0aa7.png)
эту ошибку выдает при запуске экзешника

**Comment by Bainky** [comment]
Пробовали ли вы запускать скрипт через IDLE? 
Скорее всего вы не установили один из требуемых модулей.
