### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by artourz** [Bainky/Telegram-RAT#16]
failed to execute script pyi_rth_pkgres

в pycharm вроде +- норм запускается, а вот когда создаю ехешник, вылетает ошибка
подскажите в чем может быть причина?

**Comment by Bainky** [comment]
Эта ошибка связана с pyinstaller'ом. 

**Решение:**
`pip uninstall pyinstaller`
..
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`
