### ISSUE TITLE
Не работает с даже  прокси.

### ISSUE THREAD

**Issue by MekoNix** [Bainky/Telegram-RAT#19]
Снова привет. 
Я так и не нашёл Socks прокси и просто пользовался VPN клиентом на всю систему. В старых версиях (не могу сказать в какой именно) всё работало а  теперь нет. Установив программу Socks Proxy Cheker  где можно было подключаться к прокси. Я проверял работоспособность серверов с Socks ( брал с сайта как указанно в инструкции). После проверки нескольких сайтов( TelegramWeb и Rutreker они заблокированы но с прокси работают ) я пытался их в писать в код  может это я криворукий и не смог правильно вписать  прокси или сам прокси не работает но при проверки грузит сайты . Ошибки не выдаёт только Нет подключения. Можете помочь не знаю дать рабочий прокси и научить  как его подключать к коду . 
Спасибо

**Comment by Bainky** [comment]
Привет! Возможно прокси действительно не рабочие, ибо сам с недавних пор стал замечать что большинство прокси не работает. Можете попробовать поискать рабочие прокси на [spys](http://spys.one/socks/), либо просто приобрести приватный прокси.

**Comment by MekoNix** [comment]
Поиски были обречены на провал. 
Я искал где только можно но всё не удачно. Если вы знаете где купить приватный прокси то напишите ссылку. И ещё вопросик  можно ли использовать Https и Http прокси?
Спасибо!

**Comment by Bainky** [comment]
Сам никогда не покупал прокси, но видел что продается где-то среди телеграмм-ботов. Можете также попробовать переустановить pysocks - `pip uninstall pysocks`. Если что - пишите мне в телеграмм @bainki попробуем разобраться.

**Comment by MekoNix** [comment]
Хорошо я попробую найти и переустановить если найду решения ошибки то напишу в телеграмме или если не найду а так закрываю вопрос.
