### ISSUE TITLE
Нет подключения.

### ISSUE THREAD

**Issue by A1tidote** [Bainky/Telegram-RAT#9]
Без впн не могу запустить данный скрипт. Есть ли возможность обойти это ограничение? и еще вопрос как его нормально скомпилить в exe?

**Comment by Bainky** [comment]
Телега заблокирована на территории РФ, насчет этого могу только посочувствовать и посоветовать использовать прокси. 
Чтобы скомпилировать `pip install pyinstaller` (если ошибка, то `pip uninstall -y enum34`). после установки модулей в директории со скриптом открывай консоль и вписывай `pyinstaller --onefile --noconsole RAT.py`

**Comment by AntiCheatv2** [comment]
Привет, нету подключения, использовал vpn и прокси, не помогает
